In [1]:
# import libraries
import pandas as pd
import numpy as np

# Check if data processed through pipeline is the same as data processed through NNS EDA notebook

In [3]:
# check working directory
import os
print(os.getcwd())

/Users/loistanglao/Documents/honors_thesis/code

In [4]:
# load in the data
notebook_data = pd.read_csv('../data/processed/only_nns_18_19_21_cleaned.csv')
pipeline_data = pd.read_csv('../data/processed/pipeline_18_19_21.csv')

<positron-console-cell-4>:2: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
<positron-console-cell-4>:3: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.

In [5]:
# check if both dataframes are the same
notebook_data.equals(pipeline_data)

False

In [6]:
# check shape first
print(notebook_data.shape, pipeline_data.shape)

# then find differing values
diff = notebook_data.compare(pipeline_data)
print(diff)

(444400, 23) (444400, 23)
       fwgti_natl_var       fwgti_prov                weight             \
                 self other       self      other       self      other
0                 NaN   NaN        NaN        NaN        NaN        NaN
1                 NaN   NaN        NaN        NaN  57.275002  57.275002
3                 NaN   NaN        NaN        NaN  13.775000  13.775000
5                 NaN   NaN        NaN        NaN        NaN        NaN
7                 NaN   NaN        NaN        NaN  62.775002  62.775002
...               ...   ...        ...        ...        ...        ...
444393            NaN   NaN        NaN        NaN        NaN        NaN
444394            NaN   NaN        NaN        NaN        NaN        NaN
444395            NaN   NaN        NaN        NaN        NaN        NaN
444397            NaN   NaN  34.516403  34.516403  39.400002  39.400002
444399            NaN   NaN        NaN        NaN        NaN        NaN

            height                  waist                  hip            \
              self       other       self      other      self     other
0              NaN         NaN  69.266670  69.266670  88.23333  88.23333
1              NaN         NaN        NaN        NaN       NaN       NaN
3       101.649994  101.649994        NaN        NaN       NaN       NaN
5              NaN         NaN        NaN        NaN  85.23333  85.23333
7              NaN         NaN        NaN        NaN       NaN       NaN
...            ...         ...        ...        ...       ...       ...
444393         NaN         NaN  73.366669  73.366669       NaN       NaN
444394         NaN         NaN  89.866669  89.866669       NaN       NaN
444395         NaN         NaN        NaN        NaN       NaN       NaN
444397         NaN         NaN        NaN        NaN       NaN       NaN
444399         NaN         NaN  83.233330  83.233330       NaN       NaN

              bmi
             self      other
0       19.503986  19.503986
1       20.722483  20.722483
3       13.331434  13.331434
5             NaN        NaN
7       23.612671  23.612671
...           ...        ...
444393        NaN        NaN
444394        NaN        NaN
444395  21.415711  21.415711
444397  18.521806  18.521806
444399        NaN        NaN

[232665 rows x 14 columns]

In [7]:
for col in notebook_data.columns:
    if notebook_data[col].dtype == object:  # skip string columns
        if not notebook_data[col].equals(pipeline_data[col]):
            print(f"REAL difference in column: {col}")
        else:
            print(f"OK: {col}")
    else:
        mask = notebook_data[col].notna() & pipeline_data[col].notna()
        if not np.allclose(notebook_data[col][mask], pipeline_data[col][mask], equal_nan=True):
            print(f"REAL difference in column: {col}")
        else:
            print(f"OK: {col}")

OK: regcode
OK: provhuc
OK: enns_year
OK: hhnum
OK: member_code
OK: fwgti_natl_var
OK: fwgti_prov
OK: rep_natl
OK: rep_prov
OK: ms_psucode
OK: ethnicity
OK: weight
OK: height
OK: waist
OK: hip
OK: anthro_group
OK: mos_lactation
OK: mos_preg
OK: var_value_int
OK: value_label_lower_cleaned
OK: name_lower_cleaned
OK: geometry
OK: bmi

In [8]:
pipeline_data.head()

,regcode,provhuc,enns_year,hhnum,member_code,fwgti_natl_var,fwgti_prov,rep_natl,rep_prov,ms_psucode,...,waist,hip,anthro_group,mos_lactation,mos_preg,var_value_int,value_label_lower_cleaned,name_lower_cleaned,geometry,bmi
0,1,1,2019,45958,1,2240.2327,111.251910,10,13,82,...,69.266670,88.233330,4,NaN,NaN,1,ilocos norte,ilocos norte,POLYGON ((120.42613947039311 17.89403592493226...,19.503986
1,1,1,2019,45958,2,2287.2642,109.743670,10,13,82,...,68.900002,86.666664,4,NaN,NaN,1,ilocos norte,ilocos norte,POLYGON ((120.42613947039311 17.89403592493226...,20.722483
2,1,1,2019,45958,3,2757.3613,66.695587,10,13,82,...,NaN,NaN,5,NaN,6.0,1,ilocos norte,ilocos norte,POLYGON ((120.42613947039311 17.89403592493226...,31.894474
3,1,1,2019,45958,4,3146.1538,83.465775,10,13,82,...,NaN,NaN,1,NaN,NaN,1,ilocos norte,ilocos norte,POLYGON ((120.42613947039311 17.89403592493226...,13.331434
4,1,1,2019,45959,1,2090.6460,71.073441,10,13,82,...,78.599998,92.166664,4,NaN,NaN,1,ilocos norte,ilocos norte,POLYGON ((120.42613947039311 17.89403592493226...,21.684146

# Examine differences between 2018-2021 dataset and 2015 dataset

In [19]:
# load in 2018/2019/2021 and 2015 data dictionaries
dict_2018 = pd.read_csv('../data/raw/nns/nns_18_19_21/Beatrix Eloise_Tanglao_2026-03-24055951_data-dictionary_anthrop.csv', 
                        on_bad_lines='skip')
dict_2015 = pd.read_csv('../data/raw/nns/nns_15/Beatrix Eloise_Tanglao_2026-04-15201007_data-dictionary_anthrop.csv', 
                        usecols=[0,1,2,3,4], names=['formno','variable_name','variable_label','var_value','value_label'], header=0)

In [20]:
provinces_2018 = dict_2018[dict_2018['variable_name'] == 'provhuc']
provinces_2018.head()

,formno,variable_name,variable_label,var_value,value_label
17,form21_2018,provhuc,Province and HUCs Level,1.0,Ilocos Norte
18,form21_2018,provhuc,Province and HUCs Level,2.0,Ilocos Sur
19,form21_2018,provhuc,Province and HUCs Level,3.0,La Union
20,form21_2018,provhuc,Province and HUCs Level,4.0,Pangasinan
21,form21_2018,provhuc,Province and HUCs Level,5.0,Batanes

In [21]:
dict_2015.head()

,formno,variable_name,variable_label,var_value,value_label
0,form21_2015,mos_lactation,Months of Lactation,10.0,Lactating
1,form21_2015,mos_lactation,Months of Lactation,11.0,Lactating
2,form21_2015,mos_lactation,Months of Lactation,12.0,Lactating
3,form21_2015,weight,Average Weight (kg),NaN,NaN
4,form21_2015,waist,Ave Waist Circumference (cm),NaN,NaN

In [22]:
provinces_2015 = dict_2015[dict_2015['variable_name'] == 'provcode']
provinces_2015.head()

         formno variable_name     variable_label  var_value       value_label
30  form21_2015      provcode  Name of Provinces        1.0              ABRA
31  form21_2015      provcode  Name of Provinces        2.0  AGUSAN DEL NORTE
32  form21_2015      provcode  Name of Provinces        3.0    AGUSAN DEL SUR
33  form21_2015      provcode  Name of Provinces        4.0             AKLAN
34  form21_2015      provcode  Name of Provinces        5.0             ALBAY

In [25]:
# make all the value_label values lowercase for easier comparison
provinces_2018['value_label'] = provinces_2018['value_label'].str.lower()
provinces_2015['value_label'] = provinces_2015['value_label'].str.lower()
# compare the value_label columns
merged = pd.merge(provinces_2018, provinces_2015, on='value_label', how='outer', indicator=True)
# print the results
merged[['value_label', '_merge']]

/var/folders/6j/6prg81m16mj3jnfd_9c5jcjr0000gn/T/ipykernel_14256/2633280902.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  provinces_2018['value_label'] = provinces_2018['value_label'].str.lower()
/var/folders/6j/6prg81m16mj3jnfd_9c5jcjr0000gn/T/ipykernel_14256/2633280902.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  provinces_2015['value_label'] = provinces_2015['value_label'].str.lower()

             value_label     _merge
0                   abra       both
1       agusan del norte       both
2         agusan del sur       both
3                  aklan       both
4                  albay       both
..                   ...        ...
122             zambales       both
123       zamboanga city  left_only
124  zamboanga del norte       both
125    zamboanga del sur       both
126    zamboanga sibugay       both

[127 rows x 2 columns]

In [27]:
# check how many values are in both columns
both = merged[merged['_merge'] == 'both']
both

,formno_x,variable_name_x,variable_label_x,var_value_x,value_label,formno_y,variable_name_y,variable_label_y,var_value_y,_merge
0,form21_2018,provhuc,Province and HUCs Level,100.0,abra,form21_2015,provcode,Name of Provinces,1.0,both
1,form21_2018,provhuc,Province and HUCs Level,112.0,agusan del norte,form21_2015,provcode,Name of Provinces,2.0,both
2,form21_2018,provhuc,Province and HUCs Level,113.0,agusan del sur,form21_2015,provcode,Name of Provinces,3.0,both
3,form21_2018,provhuc,Province and HUCs Level,37.0,aklan,form21_2015,provcode,Name of Provinces,4.0,both
4,form21_2018,provhuc,Province and HUCs Level,31.0,albay,form21_2015,provcode,Name of Provinces,5.0,both
...,...,...,...,...,...,...,...,...,...,...
121,form21_2018,provhuc,Province and HUCs Level,56.0,western samar,form21_2015,provcode,Name of Provinces,60.0,both
122,form21_2018,provhuc,Province and HUCs Level,16.0,zambales,form21_2015,provcode,Name of Provinces,71.0,both
124,form21_2018,provhuc,Province and HUCs Level,59.0,zamboanga del norte,form21_2015,provcode,Name of Provinces,72.0,both
125,form21_2018,provhuc,Province and HUCs Level,61.0,zamboanga del sur,form21_2015,provcode,Name of Provinces,73.0,both
126,form21_2018,provhuc,Province and HUCs Level,62.0,zamboanga sibugay,form21_2015,provcode,Name of Provinces,83.0,both

In [29]:
# make a list of values that are not in both columns
not_in_both = merged[merged['_merge'] != 'both']['value_label'].tolist()
print("Values not in both columns:")
for value in not_in_both:
    print(value)

Values not in both columns:
angeles city
bacolod city
baguio
batanes
butuan city
cagayan
cagayan de oro
cagayan province
caloocan city
cebu city
city of isabela
city of malabon
city of manila
city of marikina
city of muntinlupa
city of navotas
city of para?aque
city of pasig
city of valenzuela
davao (davao del norte)
davao city
davao del norte
davao occidental
dinagat islands
general santos city
iligan city
iloilo
iloilo city
iloilo province
isabela
isabela city
isabela province
lapu-lapu city (opon)
las pi?as city
lucena city
makati city
mandaluyong city
mandaue city
ncr - manila first district
ncr fourth district
ncr second district
ncr third district
olongapo city
pasay city
pateros
puerto princesa city
quezon
quezon city
quezon province
san juan city
sulu
tacloban city
taguig city
zamboanga city

In [30]:
# show values that are only in the 2018 dataset
only_2018 = merged[merged['_merge'] == 'left_only']['value_label'].tolist()
print("Values only in the 2018 dataset:")
for value in only_2018:
    print(value)

Values only in the 2018 dataset:
angeles city
bacolod city
baguio
batanes
butuan city
cagayan de oro
cagayan province
caloocan city
cebu city
city of isabela
city of malabon
city of manila
city of marikina
city of muntinlupa
city of navotas
city of para?aque
city of pasig
city of valenzuela
davao city
davao del norte
davao occidental
dinagat islands
general santos city
iligan city
iloilo city
iloilo province
isabela province
lapu-lapu city (opon)
las pi?as city
lucena city
makati city
mandaluyong city
mandaue city
olongapo city
pasay city
pateros
puerto princesa city
quezon city
quezon province
san juan city
tacloban city
taguig city
zamboanga city

In [31]:
# show values that are only in the 2015 dataset
only_2015 = merged[merged['_merge'] == 'right_only']['value_label'].tolist()
print("Values only in the 2015 dataset:")
for value in only_2015:
    print(value)

Values only in the 2015 dataset:
cagayan
davao (davao del norte)
iloilo
isabela
isabela city
ncr - manila first district
ncr fourth district
ncr second district
ncr third district
quezon
sulu

In [37]:
# remove the " province" suffix from the value_label column in both datasets
provinces_2018['value_label'] = provinces_2018['value_label'].str.replace(' province', '', regex=False)
provinces_2015['value_label'] = provinces_2015['value_label'].str.replace(' province', '', regex=False)
# show values that are only in the 2015 dataset using provinces_2015 and provinces_2018
merged = pd.merge(provinces_2018, provinces_2015, on='value_label', how='outer', indicator=True)
only_2015 = merged[merged['_merge'] == 'right_only']['value_label'].tolist()
print("Values only in the 2015 dataset after removing ' province' suffix:")
for value in only_2015:
    print(value)

Values only in the 2015 dataset after removing ' province' suffix:
davao (davao del norte)
isabela city
ncr - manila first district
ncr fourth district
ncr second district
ncr third district
sulu

/var/folders/6j/6prg81m16mj3jnfd_9c5jcjr0000gn/T/ipykernel_14256/4220004817.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  provinces_2018['value_label'] = provinces_2018['value_label'].str.replace(' province', '', regex=False)
/var/folders/6j/6prg81m16mj3jnfd_9c5jcjr0000gn/T/ipykernel_14256/4220004817.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  provinces_2015['value_label'] = provinces_2015['value_label'].str.replace(' province', '', regex=False)

# Check if the pre-2018 dictionaries all match each other exactly

## General Data Analysis

In [40]:
# load all pre-2018 dictionaries
dict_2015 = pd.read_csv('../data/raw/nns/nns_15/Beatrix Eloise_Tanglao_2026-04-15201007_data-dictionary_anthrop.csv', 
                        usecols=[0,1,2,3,4], names=['formno','variable_name','variable_label','var_value','value_label'], header=0)
dict_2013 = pd.read_csv('../data/raw/nns/nns_13/Beatrix Eloise_Tanglao_2026-04-15200816_data-dictionary_anthrop.csv', 
                        usecols=[0,1,2,3,4], names=['formno','variable_name','variable_label','var_value','value_label'], header=0)
dict_2011 = pd.read_csv('../data/raw/nns/nns_11/Beatrix Eloise_Tanglao_2026-04-15200227_data-dictionary_anthrop.csv', 
                        usecols=[0,1,2,3,4], names=['formno','variable_name','variable_label','var_value','value_label'], header=0)
dict_2008 = pd.read_csv('../data/raw/nns/nns_08/Beatrix Eloise_Tanglao_2026-04-15200117_data-dictionary_anthrop.csv', 
                        usecols=[0,1,2,3,4], names=['formno','variable_name','variable_label','var_value','value_label'], header=0)
dict_2003 = pd.read_csv('../data/raw/nns/nns_03/Beatrix Eloise_Tanglao_2026-04-15200000_data-dictionary_anthrop.csv', 
                        usecols=[0,1,2,3,4], names=['formno','variable_name','variable_label','var_value','value_label'], header=0)

In [41]:
dict_2015.head()

,formno,variable_name,variable_label,var_value,value_label
0,form21_2015,mos_lactation,Months of Lactation,10.0,Lactating
1,form21_2015,mos_lactation,Months of Lactation,11.0,Lactating
2,form21_2015,mos_lactation,Months of Lactation,12.0,Lactating
3,form21_2015,weight,Average Weight (kg),NaN,NaN
4,form21_2015,waist,Ave Waist Circumference (cm),NaN,NaN

In [42]:
# select only rows where variable_name is provcode or provhuc
provinces_2015 = dict_2015[dict_2015['variable_name'] == 'provcode']
provinces_2013 = dict_2013[dict_2013['variable_name'] == 'provcode']
provinces_2011 = dict_2011[dict_2011['variable_name'] == 'provcode']
provinces_2008 = dict_2008[dict_2008['variable_name'] == 'provcode']
provinces_2003 = dict_2003[dict_2003['variable_name'] == 'provcode']

In [43]:
provinces_2015

,formno,variable_name,variable_label,var_value,value_label
30,form21_2015,provcode,Name of Provinces,1.0,ABRA
31,form21_2015,provcode,Name of Provinces,2.0,AGUSAN DEL NORTE
32,form21_2015,provcode,Name of Provinces,3.0,AGUSAN DEL SUR
33,form21_2015,provcode,Name of Provinces,4.0,AKLAN
34,form21_2015,provcode,Name of Provinces,5.0,ALBAY
...,...,...,...,...,...
109,form21_2015,provcode,Name of Provinces,81.0,APAYAO
110,form21_2015,provcode,Name of Provinces,82.0,COMPOSTELA VALLEY
111,form21_2015,provcode,Name of Provinces,83.0,ZAMBOANGA SIBUGAY
112,form21_2015,provcode,Name of Provinces,97.0,ISABELA CITY
113,form21_2015,provcode,Name of Provinces,98.0,COTABATO CITY

In [44]:
provinces_2013

,formno,variable_name,variable_label,var_value,value_label
27,form21_2013,provcode,Name of Provinces,1.0,ABRA
28,form21_2013,provcode,Name of Provinces,2.0,AGUSAN DEL NORTE
29,form21_2013,provcode,Name of Provinces,3.0,AGUSAN DEL SUR
30,form21_2013,provcode,Name of Provinces,4.0,AKLAN
31,form21_2013,provcode,Name of Provinces,5.0,ALBAY
...,...,...,...,...,...
106,form21_2013,provcode,Name of Provinces,81.0,APAYAO
107,form21_2013,provcode,Name of Provinces,82.0,COMPOSTELA VALLEY
108,form21_2013,provcode,Name of Provinces,83.0,ZAMBOANGA SIBUGAY
109,form21_2013,provcode,Name of Provinces,97.0,ISABELA CITY
110,form21_2013,provcode,Name of Provinces,98.0,COTABATO CITY

In [45]:
provinces_2011

,formno,variable_name,variable_label,var_value,value_label
31,form21_2011,provcode,Name of Provinces,1.0,Abra
32,form21_2011,provcode,Name of Provinces,2.0,Agusan Del Norte
33,form21_2011,provcode,Name of Provinces,3.0,Agusan Del Sur
34,form21_2011,provcode,Name of Provinces,4.0,Aklan
35,form21_2011,provcode,Name of Provinces,5.0,Albay
...,...,...,...,...,...
110,form21_2011,provcode,Name of Provinces,81.0,Apayao
111,form21_2011,provcode,Name of Provinces,82.0,Compostela Valley
112,form21_2011,provcode,Name of Provinces,83.0,Zamboanga Sibugay
113,form21_2011,provcode,Name of Provinces,97.0,Isabela City
114,form21_2011,provcode,Name of Provinces,98.0,Cotabato City

In [46]:
provinces_2008

,formno,variable_name,variable_label,var_value,value_label
17,form21_2008,provcode,Name of Provinces,1.0,Abra
18,form21_2008,provcode,Name of Provinces,2.0,Agusan Del Norte
19,form21_2008,provcode,Name of Provinces,3.0,Agusan Del Sur
20,form21_2008,provcode,Name of Provinces,4.0,Aklan
21,form21_2008,provcode,Name of Provinces,5.0,Albay
...,...,...,...,...,...
97,form21_2008,provcode,Name of Provinces,81.0,Apayao
98,form21_2008,provcode,Name of Provinces,82.0,Compostela Valley
99,form21_2008,provcode,Name of Provinces,83.0,Zamboanga Sibugay
100,form21_2008,provcode,Name of Provinces,97.0,Isabela City
101,form21_2008,provcode,Name of Provinces,98.0,Cotabato City

In [47]:
provinces_2003

         formno variable_name     variable_label  var_value        value_label
17  form21_2003      provcode  Name of Provinces        1.0               Abra
18  form21_2003      provcode  Name of Provinces        2.0   Agusan Del Norte
19  form21_2003      provcode  Name of Provinces        3.0     Agusan Del Sur
20  form21_2003      provcode  Name of Provinces       11.0            Benguet
21  form21_2003      provcode  Name of Provinces       12.0              Bohol
..          ...           ...                ...        ...                ...
78  form21_2003      provcode  Name of Provinces       81.0             Apayao
79  form21_2003      provcode  Name of Provinces       82.0  Compostela Valley
80  form21_2003      provcode  Name of Provinces       83.0  Zamboanga Sibugay
81  form21_2003      provcode  Name of Provinces       97.0       Isabela City
82  form21_2003      provcode  Name of Provinces       98.0      Cotabato City

[66 rows x 5 columns]

In [48]:
# change index to var_value for all years
provinces_2015.set_index('var_value', inplace=True)
provinces_2013.set_index('var_value', inplace=True)
provinces_2011.set_index('var_value', inplace=True)
provinces_2008.set_index('var_value', inplace=True)
provinces_2003.set_index('var_value', inplace=True)

## 2015 and 2013

In [49]:
# check if this is true for all rows
(provinces_2015['value_label'] == provinces_2013['value_label']).all()

np.True_

In [50]:
# make the value_label column lowercase for easier comparison, and compare all of the value_label columns across all years
provinces_2015['value_label'] = provinces_2015['value_label'].str.lower()
provinces_2013['value_label'] = provinces_2013['value_label'].str.lower()
provinces_2011['value_label'] = provinces_2011['value_label'].str.lower()
provinces_2008['value_label'] = provinces_2008['value_label'].str.lower()
provinces_2003['value_label'] = provinces_2003['value_label'].str.lower()

/var/folders/6j/6prg81m16mj3jnfd_9c5jcjr0000gn/T/ipykernel_19637/2157560106.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  provinces_2015['value_label'] = provinces_2015['value_label'].str.lower()
/var/folders/6j/6prg81m16mj3jnfd_9c5jcjr0000gn/T/ipykernel_19637/2157560106.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  provinces_2013['value_label'] = provinces_2013['value_label'].str.lower()
/var/folders/6j/6prg81m16mj3jnfd_9c5jcjr0000gn/T/ipykernel_19637/2157560106.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  provinces_2011['value_label'] = provinces_2011['value_label'].str.lower()
/var/folders/6j/6prg81m16mj3jnfd_9c5jcjr0000gn/T/ipykernel_19637/2157560106.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  provinces_2008['value_label'] = provinces_2008['value_label'].str.lower()
/var/folders/6j/6prg81m16mj3jnfd_9c5jcjr0000gn/T/ipykernel_19637/2157560106.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  provinces_2003['value_label'] = provinces_2003['value_label'].str.lower()

In [51]:
# compare the value_label columns across all years
(provinces_2015['value_label'] == provinces_2013['value_label']).all()

np.True_

## 2015 and 2011

In [52]:
(provinces_2015['value_label'] == provinces_2011['value_label']).all()

np.False_

In [53]:
provinces_2011.head()

                formno variable_name     variable_label       value_label
var_value
1.0        form21_2011      provcode  Name of Provinces              abra
2.0        form21_2011      provcode  Name of Provinces  agusan del norte
3.0        form21_2011      provcode  Name of Provinces    agusan del sur
4.0        form21_2011      provcode  Name of Provinces             aklan
5.0        form21_2011      provcode  Name of Provinces             albay

In [54]:
provinces_2015.head()

                formno variable_name     variable_label       value_label
var_value
1.0        form21_2015      provcode  Name of Provinces              abra
2.0        form21_2015      provcode  Name of Provinces  agusan del norte
3.0        form21_2015      provcode  Name of Provinces    agusan del sur
4.0        form21_2015      provcode  Name of Provinces             aklan
5.0        form21_2015      provcode  Name of Provinces             albay

In [55]:
# check what value_label are in 2015 but not in 2011
merged = pd.merge(provinces_2015, provinces_2011, on='value_label', how='outer', indicator=True)
only_2015 = merged[merged['_merge'] == 'left_only']['value_label'].tolist()
only_2015

['apayao',
 'aurora',
 'batangas',
 'benguet',
 'biliran',
 'bohol',
 'bukidnon',
 'bulacan',
 'cagayan',
 'camarines norte',
 'camarines sur',
 'camiguin',
 'capiz',
 'catanduanes',
 'cavite',
 'cebu',
 'compostela valley',
 'cotabato city',
 'davao (davao del norte)',
 'davao del sur',
 'davao oriental',
 'eastern samar',
 'guimaras',
 'ifugao',
 'ilocos norte',
 'ilocos sur',
 'iloilo',
 'isabela',
 'isabela city',
 'kalinga',
 'la union',
 'laguna',
 'lanao del norte',
 'lanao del sur',
 'leyte',
 'maguindanao',
 'marinduque',
 'masbate',
 'misamis occidental',
 'misamis oriental',
 'mountain province',
 'ncr - manila first district',
 'ncr fourth district',
 'ncr second district',
 'ncr third district',
 'negros occidental',
 'negros oriental',
 'north cotabato',
 'northern samar',
 'nueva ecija',
 'nueva vizcaya',
 'occidental mindoro',
 'oriental mindoro',
 'palawan',
 'pampanga',
 'pangasinan',
 'quezon',
 'quirino',
 'rizal',
 'romblon',
 'sarangani',
 'siquijor',
 'sorsogon',
 'south cotabato',
 'southern leyte',
 'sultan kudarat',
 'sulu',
 'surigao del norte',
 'surigao del sur',
 'tarlac',
 'tawi-tawi',
 'western samar',
 'zambales',
 'zamboanga del norte',
 'zamboanga del sur',
 'zamboanga sibugay']

In [56]:
# check what value_label are in 2011 but not in 2015
only_2011 = merged[merged['_merge'] == 'right_only']['value_label'].tolist()
only_2011

[' apayao',
 ' aurora',
 ' batangas',
 ' benguet',
 ' biliran',
 ' bohol',
 ' bukidnon',
 ' bulacan',
 ' cagayan',
 ' camarines norte',
 ' camarines sur',
 ' camiguin',
 ' capiz',
 ' catanduanes',
 ' cavite',
 ' cebu',
 ' compostela valley',
 ' cotabato city',
 ' davao (davao del norte)',
 ' davao del sur',
 ' davao oriental',
 ' eastern samar',
 ' guimaras',
 ' ifugao',
 ' ilocos norte',
 ' ilocos sur',
 ' iloilo',
 ' isabela',
 ' isabela city',
 ' kalinga',
 ' la union',
 ' laguna',
 ' lanao del norte',
 ' lanao del sur',
 ' leyte',
 ' maguindanao',
 ' marinduque',
 ' masbate',
 ' misamis occidental',
 ' misamis oriental',
 ' mountain province',
 ' ncr - manila first district',
 ' ncr fourth district',
 ' ncr second district',
 ' ncr third district',
 ' negros occidental',
 ' negros oriental',
 ' north cotabato',
 ' northern samar',
 ' nueva ecija',
 ' nueva vizcaya',
 ' occidental mindoro',
 ' oriental mindoro',
 ' palawan',
 ' pampanga',
 ' pangasinan',
 ' quezon',
 ' quirino',
 ' rizal',
 ' romblon',
 ' sarangani',
 ' siquijor',
 ' sorsogon',
 ' south cotabato',
 ' southern leyte',
 ' sultan kudarat',
 ' sulu',
 ' surigao del norte',
 ' surigao del sur',
 ' tarlac',
 ' tawi-tawi',
 ' western samar',
 ' zambales',
 ' zamboanga del norte',
 ' zamboanga del sur',
 ' zamboanga sibugay']

In [57]:
# edit the value_label column in provinces_2011 so that if there is a space before the first symbol, it is removed
provinces_2011['value_label'] = provinces_2011['value_label'].str.lstrip()

/var/folders/6j/6prg81m16mj3jnfd_9c5jcjr0000gn/T/ipykernel_19637/1333784392.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  provinces_2011['value_label'] = provinces_2011['value_label'].str.lstrip()

In [58]:
provinces_2011['value_label'].tolist()

['abra',
 'agusan del norte',
 'agusan del sur',
 'aklan',
 'albay',
 'antique',
 'basilan',
 'bataan',
 'batangas',
 'benguet',
 'bohol',
 'bukidnon',
 'bulacan',
 'cagayan',
 'camarines norte',
 'camarines sur',
 'camiguin',
 'capiz',
 'catanduanes',
 'cavite',
 'cebu',
 'davao (davao del norte)',
 'davao del sur',
 'davao oriental',
 'eastern samar',
 'ifugao',
 'ilocos norte',
 'ilocos sur',
 'iloilo',
 'isabela',
 'kalinga',
 'la union',
 'laguna',
 'lanao del norte',
 'lanao del sur',
 'leyte',
 'maguindanao',
 'ncr - manila first district',
 'marinduque',
 'masbate',
 'misamis occidental',
 'misamis oriental',
 'mountain province',
 'negros occidental',
 'negros oriental',
 'north cotabato',
 'northern samar',
 'nueva ecija',
 'nueva vizcaya',
 'occidental mindoro',
 'oriental mindoro',
 'palawan',
 'pampanga',
 'pangasinan',
 'quezon',
 'quirino',
 'rizal',
 'romblon',
 'western samar',
 'siquijor',
 'sorsogon',
 'south cotabato',
 'southern leyte',
 'sultan kudarat',
 'sulu',
 'surigao del norte',
 'surigao del sur',
 'tarlac',
 'tawi-tawi',
 'zambales',
 'zamboanga del norte',
 'zamboanga del sur',
 'ncr second district',
 'ncr third district',
 'ncr fourth district',
 'aurora',
 'biliran',
 'guimaras',
 'sarangani',
 'apayao',
 'compostela valley',
 'zamboanga sibugay',
 'isabela city',
 'cotabato city']

In [59]:
merged_again = pd.merge(provinces_2015, provinces_2011, on='value_label', how='outer', indicator=True)
only_2015_again = merged_again[merged_again['_merge'] == 'left_only']['value_label'].tolist()
only_2011_again = merged_again[merged_again['_merge'] == 'right_only']['value_label'].tolist()

In [60]:
only_2015_again

[]

In [61]:
only_2011_again

[]

## 2015 and 2008

In [64]:
provinces_2008

                formno variable_name     variable_label        value_label
var_value
1.0        form21_2008      provcode  Name of Provinces               abra
2.0        form21_2008      provcode  Name of Provinces   agusan del norte
3.0        form21_2008      provcode  Name of Provinces     agusan del sur
4.0        form21_2008      provcode  Name of Provinces              aklan
5.0        form21_2008      provcode  Name of Provinces              albay
...                ...           ...                ...                ...
81.0       form21_2008      provcode  Name of Provinces             apayao
82.0       form21_2008      provcode  Name of Provinces  compostela valley
83.0       form21_2008      provcode  Name of Provinces  zamboanga sibugay
97.0       form21_2008      provcode  Name of Provinces       isabela city
98.0       form21_2008      provcode  Name of Provinces      cotabato city

[85 rows x 4 columns]

In [65]:
provinces_2015

                formno variable_name     variable_label        value_label
var_value
1.0        form21_2015      provcode  Name of Provinces               abra
2.0        form21_2015      provcode  Name of Provinces   agusan del norte
3.0        form21_2015      provcode  Name of Provinces     agusan del sur
4.0        form21_2015      provcode  Name of Provinces              aklan
5.0        form21_2015      provcode  Name of Provinces              albay
...                ...           ...                ...                ...
81.0       form21_2015      provcode  Name of Provinces             apayao
82.0       form21_2015      provcode  Name of Provinces  compostela valley
83.0       form21_2015      provcode  Name of Provinces  zamboanga sibugay
97.0       form21_2015      provcode  Name of Provinces       isabela city
98.0       form21_2015      provcode  Name of Provinces      cotabato city

[84 rows x 4 columns]

In [62]:
(provinces_2015['value_label'] == provinces_2008['value_label']).all()

ValueError: Can only compare identically-labeled Series objects

In [66]:
# check what values are in 2015 but not in 2008
merged = pd.merge(provinces_2015, provinces_2008, on='value_label', how='outer', indicator=True)
only_2015 = merged[merged['_merge'] == 'left_only']['value_label'].tolist()
only_2015

[]

In [67]:
# check what values are in 2008 but not in 2015
only_2008 = merged[merged['_merge'] == 'right_only']['value_label'].tolist()
only_2008

['batanes']

In [69]:
# remove batanes from provinces_2008 and check again
provinces_2008 = provinces_2008[provinces_2008['value_label'] != 'batanes']
merged = pd.merge(provinces_2015, provinces_2008, on='value_label', how='outer', indicator=True)
only_2015 = merged[merged['_merge'] == 'left_only']['value_label'].tolist()
only_2008 = merged[merged['_merge'] == 'right_only']['value_label'].tolist()
only_2015

[]

In [71]:
only_2008

[]

## 2015 and 2003

In [72]:
# check if provinces_2015 and provinces_2003 have the same value_label values
(provinces_2015['value_label'] == provinces_2003['value_label']).all()

ValueError: Can only compare identically-labeled Series objects

In [74]:
# check what values are in 2015 but not in 2003
merged = pd.merge(provinces_2015, provinces_2003, on='value_label', how='outer', indicator=True)
only_2015 = merged[merged['_merge'] == 'left_only']['value_label'].tolist()
only_2015

['aklan',
 'albay',
 'antique',
 'basilan',
 'bataan',
 'batangas',
 'bukidnon',
 'bulacan',
 'camarines norte',
 'cebu',
 'davao (davao del norte)',
 'davao del sur',
 'davao oriental',
 'ilocos norte',
 'ilocos sur',
 'iloilo',
 'isabela',
 'kalinga',
 'la union']

In [79]:
# check length of only_2015
len(only_2015)

19

In [76]:
# check what values are in 2003 but not in 2015
only_2003 = merged[merged['_merge'] == 'right_only']['value_label'].tolist()
only_2003

[]

In [77]:
provinces_2015

                formno variable_name     variable_label        value_label
var_value
1.0        form21_2015      provcode  Name of Provinces               abra
2.0        form21_2015      provcode  Name of Provinces   agusan del norte
3.0        form21_2015      provcode  Name of Provinces     agusan del sur
4.0        form21_2015      provcode  Name of Provinces              aklan
5.0        form21_2015      provcode  Name of Provinces              albay
...                ...           ...                ...                ...
81.0       form21_2015      provcode  Name of Provinces             apayao
82.0       form21_2015      provcode  Name of Provinces  compostela valley
83.0       form21_2015      provcode  Name of Provinces  zamboanga sibugay
97.0       form21_2015      provcode  Name of Provinces       isabela city
98.0       form21_2015      provcode  Name of Provinces      cotabato city

[84 rows x 4 columns]

In [78]:
provinces_2003

                formno variable_name     variable_label        value_label
var_value
1.0        form21_2003      provcode  Name of Provinces               abra
2.0        form21_2003      provcode  Name of Provinces   agusan del norte
3.0        form21_2003      provcode  Name of Provinces     agusan del sur
11.0       form21_2003      provcode  Name of Provinces            benguet
12.0       form21_2003      provcode  Name of Provinces              bohol
...                ...           ...                ...                ...
81.0       form21_2003      provcode  Name of Provinces             apayao
82.0       form21_2003      provcode  Name of Provinces  compostela valley
83.0       form21_2003      provcode  Name of Provinces  zamboanga sibugay
97.0       form21_2003      provcode  Name of Provinces       isabela city
98.0       form21_2003      provcode  Name of Provinces      cotabato city

[66 rows x 4 columns]

In [81]:
# subtract the lengths of provinces_2015 and provinces_2003
len(provinces_2015) - len(provinces_2003)

18

In [82]:
# figure out the difference between the 2015 and 2013 datasets
merged

,formno_x,variable_name_x,variable_label_x,value_label,formno_y,variable_name_y,variable_label_y,_merge
0,form21_2015,provcode,Name of Provinces,abra,form21_2003,provcode,Name of Provinces,both
1,form21_2015,provcode,Name of Provinces,agusan del norte,form21_2003,provcode,Name of Provinces,both
2,form21_2015,provcode,Name of Provinces,agusan del sur,form21_2003,provcode,Name of Provinces,both
3,form21_2015,provcode,Name of Provinces,aklan,NaN,NaN,NaN,left_only
4,form21_2015,provcode,Name of Provinces,albay,NaN,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...
80,form21_2015,provcode,Name of Provinces,western samar,form21_2003,provcode,Name of Provinces,both
81,form21_2015,provcode,Name of Provinces,zambales,form21_2003,provcode,Name of Provinces,both
82,form21_2015,provcode,Name of Provinces,zamboanga del norte,form21_2003,provcode,Name of Provinces,both
83,form21_2015,provcode,Name of Provinces,zamboanga del sur,form21_2003,provcode,Name of Provinces,both
84,form21_2015,provcode,Name of Provinces,zamboanga sibugay,form21_2003,provcode,Name of Provinces,both

In [84]:
# check how many values are in both datasets
both = merged[merged['_merge'] == 'both']
both

,formno_x,variable_name_x,variable_label_x,value_label,formno_y,variable_name_y,variable_label_y,_merge
0,form21_2015,provcode,Name of Provinces,abra,form21_2003,provcode,Name of Provinces,both
1,form21_2015,provcode,Name of Provinces,agusan del norte,form21_2003,provcode,Name of Provinces,both
2,form21_2015,provcode,Name of Provinces,agusan del sur,form21_2003,provcode,Name of Provinces,both
6,form21_2015,provcode,Name of Provinces,apayao,form21_2003,provcode,Name of Provinces,both
7,form21_2015,provcode,Name of Provinces,aurora,form21_2003,provcode,Name of Provinces,both
...,...,...,...,...,...,...,...,...
80,form21_2015,provcode,Name of Provinces,western samar,form21_2003,provcode,Name of Provinces,both
81,form21_2015,provcode,Name of Provinces,zambales,form21_2003,provcode,Name of Provinces,both
82,form21_2015,provcode,Name of Provinces,zamboanga del norte,form21_2003,provcode,Name of Provinces,both
83,form21_2015,provcode,Name of Provinces,zamboanga del sur,form21_2003,provcode,Name of Provinces,both
84,form21_2015,provcode,Name of Provinces,zamboanga sibugay,form21_2003,provcode,Name of Provinces,both

In [86]:
# check how many values are in 2015 but not in 2013
only_2015 = merged[merged['_merge'] == 'left_only']['value_label'].tolist()
len(only_2015)

19

In [87]:
# check how many values are in 2013 but not in 2015
only_2013 = merged[merged['_merge'] == 'right_only']['value_label'].tolist()
len(only_2013)

0

In [88]:
# check how many values are not in either dataset
neither = merged[merged['_merge'] == 'neither']
len(neither)

0

In [89]:
provinces_2015[provinces_2015['value_label'].duplicated(keep=False)]

Empty DataFrame
Columns: [formno, variable_name, variable_label, value_label]
Index: []

In [91]:
# check if provinces_2003 has duplicates in other columns
provinces_2003[provinces_2003.duplicated(keep=False)]

                formno variable_name     variable_label value_label
var_value
15.0       form21_2003      provcode  Name of Provinces     cagayan
16.0       form21_2003      provcode  Name of Provinces     cagayan

# Match the 2015 dataset with the 2018 w/ provinces dataset

In [107]:
# load in 2015 dataset and 2018 with provinces dataset
dict_2015 = pd.read_csv('../data/raw/nns/nns_15/Beatrix Eloise_Tanglao_2026-04-15201007_data-dictionary_anthrop.csv', 
                        usecols=[0,1,2,3,4], names=['formno','variable_name','variable_label','var_value','value_label'], header=0)
notebook_data = pd.read_csv('../data/processed/final_data.csv')

ParserError: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.

In [108]:
provinces_2015 = dict_2015[dict_2015['variable_name'] == 'provcode']
# make the value_label column lowercase for easier comparison
provinces_2015['value_label'] = provinces_2015['value_label'].str.lower()

/var/folders/6j/6prg81m16mj3jnfd_9c5jcjr0000gn/T/ipykernel_19637/1175125104.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  provinces_2015['value_label'] = provinces_2015['value_label'].str.lower()

In [109]:
dict_2015.head()

,formno,variable_name,variable_label,var_value,value_label
0,form21_2015,mos_lactation,Months of Lactation,10.0,Lactating
1,form21_2015,mos_lactation,Months of Lactation,11.0,Lactating
2,form21_2015,mos_lactation,Months of Lactation,12.0,Lactating
3,form21_2015,weight,Average Weight (kg),NaN,NaN
4,form21_2015,waist,Ave Waist Circumference (cm),NaN,NaN

In [110]:
notebook_data.head()

,regcode,provhuc,enns_year,hhnum,member_code,fwgti_natl_var,fwgti_prov,rep_natl,rep_prov,ms_psucode,...,waist,hip,anthro_group,mos_lactation,mos_preg,var_value_int,value_label_lower_cleaned,name_lower_cleaned,geometry,bmi
0,1,1,2019,45958,1,2240.2327,111.251910,10,13,82,...,69.266670,88.233330,4,NaN,NaN,1,ilocos norte,ilocos norte,POLYGON ((120.42613947039311 17.89403592493226...,19.503986
1,1,1,2019,45958,2,2287.2642,109.743670,10,13,82,...,68.900002,86.666664,4,NaN,NaN,1,ilocos norte,ilocos norte,POLYGON ((120.42613947039311 17.89403592493226...,20.722483
2,1,1,2019,45958,3,2757.3613,66.695587,10,13,82,...,NaN,NaN,5,NaN,6.0,1,ilocos norte,ilocos norte,POLYGON ((120.42613947039311 17.89403592493226...,31.894474
3,1,1,2019,45958,4,3146.1538,83.465775,10,13,82,...,NaN,NaN,1,NaN,NaN,1,ilocos norte,ilocos norte,POLYGON ((120.42613947039311 17.89403592493226...,13.331434
4,1,1,2019,45959,1,2090.6460,71.073441,10,13,82,...,78.599998,92.166664,4,NaN,NaN,1,ilocos norte,ilocos norte,POLYGON ((120.42613947039311 17.89403592493226...,21.684146

In [111]:
notebook_name_code = notebook_data[['provhuc', 'name_lower_cleaned']].drop_duplicates()
notebook_name_code

        provhuc    name_lower_cleaned
0             1          ilocos norte
4381          2            ilocos sur
7969          3              la union
12500         4            pangasinan
17270         5               batanes
...         ...                   ...
422236       26    occidental mindoro
426536       27      oriental mindoro
431348       28               palawan
433819       29  puerto princesa city
439256       30               romblon

[116 rows x 2 columns]

In [112]:
# sort notebook_name_code by provhuc
notebook_name_code.sort_values('provhuc', inplace=True)
notebook_name_code

        provhuc name_lower_cleaned
0             1       ilocos norte
4381          2         ilocos sur
7969          3           la union
12500         4         pangasinan
17270         5            batanes
...         ...                ...
391374      112   agusan del norte
401424      113     agusan del sur
406373      114  surigao del norte
410597      115    surigao del sur
415430      116                NaN

[116 rows x 2 columns]

In [113]:
# check what value_label are in 2015 but not in name_lower_cleaned in notebook_name_code
merged = pd.merge(provinces_2015, notebook_name_code, left_on='value_label', right_on='name_lower_cleaned', how='outer', indicator=True)
only_2015 = merged[merged['_merge'] == 'left_only']['value_label'].tolist()
print("Values in 2015 but not in notebook_name_code:")
for value in only_2015:
    print(value)
# check what name_lower_cleaned are in notebook_name_code but not in 2015
only_notebook = merged[merged['_merge'] == 'right_only']['name_lower_cleaned'].tolist()
print("Values in notebook_name_code but not in 2015:")
for value in only_notebook:
    print(value)

Values in 2015 but not in notebook_name_code:
cagayan
davao (davao del norte)
iloilo
isabela
isabela city
ncr - manila first district
ncr fourth district
ncr second district
ncr third district
north cotabato
quezon
sulu
western samar
Values in notebook_name_code but not in 2015:
angeles city
bacolod city
baguio city
batanes
butuan city
cagayan de oro city
cagayan province
caloocan city
cebu city
cotabato province
davao city
davao del norte
general santos city
iligan city
iloilo city
iloilo province
isabela province
lapu-lapu city
las pinas city
lucena city
makati city
malabon city
mandaue city
manila city
marikina city
muntinlupa city
navotas city
olongapo city
paranaque city
pasay city
pasig city
pateros
puerto princesa city
quezon city
quezon province
samar
san juan city
tacloban city
taguig city
valenzuela city
zamboanga city
nan
nan
nan
nan

In [ ]:
# check what value_label are in 2015 but not in name_lower_cleaned in notebook_name_code
merged = pd.merge(provinces_2015, notebook_name_code, left_on='value_label', right_on='name_lower_cleaned', how='outer', indicator=True)
only_2015 = merged[merged['_merge'] == 'left_only']['value_label'].tolist()
print("Values in 2015 but not in notebook_name_code:")
for value in only_2015:
    print(value)
# check what name_lower_cleaned are in notebook_name_code but not in 2015
only_notebook = merged[merged['_merge'] == 'right_only']['name_lower_cleaned'].tolist()
print("Values in notebook_name_code but not in 2015:")
for value in only_notebook:
    print(value)

In [114]:
# get the var_value and value_label data associated with only_2015 and only_notebook
merged[merged['_merge'] == 'left_only']['value_label']

21                         cagayan
36         davao (davao del norte)
48                          iloilo
51                         isabela
52                    isabela city
76     ncr - manila first district
77             ncr fourth district
78             ncr second district
79              ncr third district
82                  north cotabato
97                          quezon
111                           sulu
119                  western samar
Name: value_label, dtype: object

In [117]:
# idea: merge 2015 and notebook on provhuc and var_value
merged_nums = pd.merge(provinces_2015, notebook_name_code, left_on='var_value', right_on='provhuc', how='outer', indicator=True)
merged_nums[merged_nums['_merge'] == 'both'][['var_value', 'value_label', 'name_lower_cleaned', 'provhuc']]

    var_value        value_label name_lower_cleaned  provhuc
0         1.0               abra       ilocos norte        1
1         2.0   agusan del norte         ilocos sur        2
2         3.0     agusan del sur           la union        3
3         4.0              aklan         pangasinan        4
4         5.0              albay            batanes        5
..        ...                ...                ...      ...
80       81.0             apayao          sarangani       81
81       82.0  compostela valley      cotabato city       82
82       83.0  zamboanga sibugay        manila city       83
96       97.0       isabela city            pateros       97
97       98.0      cotabato city    muntinlupa city       98

[84 rows x 4 columns]

this does not work because the codes are not the same :(